### PR TITLE
Added Bengali translations to translation.js

### PR DESCRIPTION
**Pull request by BinTofajjal**

### CODE REVIEW

**Review by kurt-liao — COMMENTED** [review]
Hi @BinTofajjal , thanks for contributing!

Since there's a typo in `statcard.title`, I think the locale would be `bn` not `bd` right? Could you please fix it out, and I'll merge it, thanks a lot!

BTW, it's really help me for starring the repo😇.

Happy Hacktoberfest!

**Comment by BinTofajjal** [comment]
> Hi @BinTofajjal , thanks for contributing!
> 
> Since there's a typo in `statcard.title`, I think the locale would be `bn` not `bd` right? Could you please fix it out, and I'll merge it, thanks a lot!
> 
> BTW, it's really help me for starring the repo😇.
> 
> Happy Hacktoberfest!

I've fixed the issue.

**Comment by kurt-liao** [comment]
LGTM, thanks!

**Comment by kurt-liao** [comment]
@all-contributors please add @BinTofajjal for code

**Pull request merged**
