### PR TITLE
translated to German

### PR DESCRIPTION
**Pull request by sarequl**

### CODE REVIEW

**Review by kurt-liao — APPROVED** [review]
Hi @sarequl, thanks for contributing!

**Comment by kurt-liao** [comment]
@all-contributors please add @sarequl for translation

**Comment by sarequl** [comment]
Please label this as hacktoberfest accepted

**Comment by kurt-liao** [comment]
> Please label this as hacktoberfest accepted

Sure, I forgot it.

**Comment by sarequl** [comment]
Thank You ❤️

**Pull request merged**
